force-app/main/default/objects/Dynamic_Apex_Trigger_Configuration__c/Dynamic_Apex_Trigger_Configuration__c.object-meta.xml
<CustomObject>
    <label>Dynamic Apex Trigger Configuration</label>
    <nameField>
        <displayFormat>TrigConfig-{0000}</displayFormat>
        <label>Dynamic Apex Trigger Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dynamic Apex Trigger Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dynamic_Apex_Trigger_Configuration__c/fields/Deployed__c.field-meta.xml
<CustomField>
    <fullName>Deployed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use this to indicate whether or not this configuration is active. If left unchecked, this configuration will not factor into future dynamic trigger generations.</description>
    <inlineHelpText>Use this to indicate whether or not this configuration is active.</inlineHelpText>
    <label>Deployed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dynamic_Apex_Trigger_Configuration__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <description>Use this to identify which field on the above identified standard / custom object to tie the trigger to. Make sure to use the API name of the field.</description>
    <inlineHelpText>Use this to identify which field on the above identified standard / custom object to tie the trigger to.</inlineHelpText>
    <label>Field</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dynamic_Apex_Trigger_Configuration__c/fields/Field_Condition__c.field-meta.xml
<CustomField>
    <fullName>Field_Condition__c</fullName>
    <description>Use this to identify the value on the previously identified field that will cause the trigger to run. The script will look for an exact match.</description>
    <inlineHelpText>Use this to identify the value on the previously identified field that will cause the trigger to run. The script will look for an exact match.</inlineHelpText>
    <label>Field Condition</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dynamic_Apex_Trigger_Configuration__c/fields/On_Complete_Callback__c.field-meta.xml
<CustomField>
    <fullName>On_Complete_Callback__c</fullName>
    <description>Use this to identify the class or method to run when the trigger conditions are met. If there is an error here, the trigger will not be generated, so make sure to follow proper Apex syntax.</description>
    <inlineHelpText>Use this to identify the class or method to run when the trigger conditions are met. If there is an error here, the trigger will not be generated, so make sure to follow proper Apex syntax.</inlineHelpText>
    <label>On Complete Callback</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dynamic_Apex_Trigger_Configuration__c/fields/SObject_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Name__c</fullName>
    <description>Use this to identify the standard / custom object to associate with the trigger. Make sure to use the API name.</description>
    <inlineHelpText>Use this to identify the standard / custom object to associate with the trigger. Make sure to use the API name.</inlineHelpText>
    <label>SObject Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApexTriggerBuilderTest.cls
@isTest
public with sharing class ApexTriggerBuilderTest {
    static testmethod void testBuild() {
        Dynamic_Apex_Trigger_Configuration__c config = (Dynamic_Apex_Trigger_Configuration__c) TestDataFactory.createSObject('Dynamic_Apex_Trigger_Configuration__c', new Map<String, Object>{
            'Deployed__c' => true,
            'SObject_Name__c' => 'Account',
            'Field__c' => 'Name',
            'Field_Condition__c' => 'Test',
            'On_Complete_Callback__c' => 'new ApexTriggerBuilder()' 
        });

        ApexTriggerBuilder.ApexTriggerBuilderRequest request = new ApexTriggerBuilder.ApexTriggerBuilderRequest();
        request.recordId = config.Id;
        List<ApexTriggerBuilder.ApexTriggerBuilderRequest> requests = new List<ApexTriggerBuilder.ApexTriggerBuilderRequest>();
        requests.add(request);

        ApexTriggerBuilder.buildTriggers(requests);
        String asyncRequestId = '123';

        System.assertEquals('123', asyncRequestId, 'Ids do not match');
        MetadataService.DeployResult check = ApexTriggerBuilder.checkAsyncRequest(asyncRequestId);
        System.assertEquals(null, check, 'Results do not match');
    }
    static testmethod void testNoBuild() {
        ApexTriggerBuilder.ApexTriggerBuilderRequest request = new ApexTriggerBuilder.ApexTriggerBuilderRequest();
        List<ApexTriggerBuilder.ApexTriggerBuilderRequest> requests = new List<ApexTriggerBuilder.ApexTriggerBuilderRequest>();
        requests.add(request);

        ApexTriggerBuilder.buildTriggers(requests);
        String asyncRequestId = null;

        System.assertEquals(null, asyncRequestId, 'Ids do not match');
    }
}